### ISSUE TITLE
Please give link to the original project

### ISSUE THREAD

**Issue by postacik** [sharpbrowser/SharpBrowser#1]
This project uses most of the parts of the Chromium Tor Browser on CodeProject.

Please respect other's work and give a link to the original project.

http://www.codeproject.com/Articles/1074435/Chromium-CefSharp-Tor-Browser

**Comment by hgupta9** [comment]
Yes I used it as a start but most of the code and graphics was changed. Open the code yourself and take a look. The JSON serializer you used did not work with the latest CefSharp. All the handlers had to be rewritten for CefSharp 50+ (I have yet to upload this version). Even the Tab Control was entirely modified to give a Google Chrome-like look and feel.

Only the downloads feature is significantly the same. I'll add a thank you for that feature.

**Comment by postacik** [comment]
Thank you.
It could be better if you could give a link to the CodeProject page.

http://www.codeproject.com/Articles/1074435/Chromium-CefSharp-Tor-Browser
