### ISSUE TITLE
chinese show

### ISSUE THREAD

**Issue by xyw1005** [sharpbrowser/SharpBrowser#14]
need those settings:
settings.Locale = "zh-CN";
 settings.AcceptLanguageList = "zh-CN";

**Comment by fjch1997** [comment]
Locale should be determined by operating system settings instead of being hard coded.

**Comment by robinrodricks** [comment]
You can set this in [RequestHandler](https://github.com/sharpbrowser/SharpBrowser/blob/master/src/Handlers/RequestHandler.cs). See this [thread ](https://github.com/cefsharp/CefSharp/issues/231)for more info.
