### ISSUE TITLE
TitleChanged  why Run twice?

### ISSUE THREAD

**Issue by robyle** [sharpbrowser/SharpBrowser#15]
Case：
I declare a variable 'LoginTitleChangeCount', this variable I just  used on one function place.  
 
Why My LogToText(' ..... ')  Function will be run twice？
![default](https://user-images.githubusercontent.com/11662528/40896808-e8224bc8-67e9-11e8-81e5-e4cdfbd94c14.png)

中文补充说明:
我将TitleChanged的事件上绑定了一个方法，为什么明明执行过一次 LoginTitleChangeCount+1
 后，LoginTitleChangeCount 不会再等于1了。而判断是否等于1的逻辑里面的方法会再次执行？ 我标识对这个事件加载次数和计数值疑惑。

**Comment by robinrodricks** [comment]
It may be run multiple times, whenever the web page changes its title we
will trigger that event.

**Comment by robyle** [comment]
you know ,I have changed the variable of 'LoginTitleChangeCount'.   So I think   the second times to change the variable of 'LoginTitleChangeCount' will be 2.  so Why  LogToText  method will run twice?  How can I make it run once ? just run one time of 'LogToText' function.
