### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by servusDei2018** [sharpbrowser/SharpBrowser#17]
Where would I find the file in which the web (http) connection is handled? Does it use Microsoft's WebClient(), HttpClient(), or a custom one?

**Comment by robinrodricks** [comment]
That is the internal implementation of Chromium web browser. You can't
change that. There may be a handler but not sure. Consult the cefsharp
docs. What are you trying to do?

**Comment by servusDei2018** [comment]
I am trying to implement my own version of the WebClient() to handle a new http protocol I'm developing, and want a browser that will support that.

**Comment by robinrodricks** [comment]
Check cefsharp, it probably has a handler for that...

**Comment by robinrodricks** [comment]
And we are using cefsharp internally so it's fine

**Comment by servusDei2018** [comment]
Sure. Thanks
