### ISSUE TITLE
when open a page in new tab  "HTTP_REFERER"  will be lost

### ISSUE THREAD

**Issue by c20000c** [sharpbrowser/SharpBrowser#2]
when open a page in new tab  "HTTP_REFERER"  will be lost。
if open a page by popup "HTTP_REFERER"  will be ok. 
any one can help me?  thx.

**Comment by lwdred** [comment]
when i click a link to download a file.if the file is a pdf,it can be show on a new tab.but the others can not be show and can not  be download automatic.any one can hele me? tks

**Comment by hgupta9** [comment]
I've written the code for this. Can you check if it works? In some cases it may fail but thats a bug in CefSharp (https://github.com/cefsharp/CefSharp/issues/1997)

**Comment by amaitland** [comment]
The sharpbrowser RequestHandler implementation is incorrect, the CefSharp source contains a valid example. Before you starting opening issues and asserting there a bugs in other projects compare your code to the reference example please.

**Comment by hgupta9** [comment]
@amaitland - Dude, chill! This is a lonely project and your CefSharp project is not being defamed in any way! I just had to explain my changes to the OP!
