### ISSUE TITLE
can not download files automatic

### ISSUE THREAD

**Issue by toohandsome** [sharpbrowser/SharpBrowser#22]
1.when i click a link to download a file. it will  open a new tab,and do nothing. 
2.when i click downloads , it will crash
![2](https://user-images.githubusercontent.com/46422252/58371591-49d9eb00-7f45-11e9-945d-54497b62c4fc.png)

![1](https://user-images.githubusercontent.com/46422252/58371589-40e91980-7f45-11e9-9793-f0c98cbb483a.png)

**Comment by sgbhavsar** [comment]
It seems that there is breaking change in cefsharp to register asynchjsobject which requires to be updated.

**Comment by robinrodricks** [comment]
@dpbiz  all fixes implemented, thanks.
