### ISSUE TITLE
FATabStrip

### ISSUE THREAD

**Issue by Vet-Qiu** [sharpbrowser/SharpBrowser#24]
Hello

I'd like to ask

1. Can tabs be hidden?

2. Can the background color of the tab be changed?

**Comment by maifeeulasad** [comment]
1. If a tab is hidden how will you access that??
     A new option to access hidden tabs?
2. Of Course.

**Comment by Vet-Qiu** [comment]
1. Full screen effect
If panel overrides, the custom control hierarchy cannot be at the top level
 2. Setting BackColor has no effect
