### ISSUE TITLE
RequestHandler  & SchemeHandler

### ISSUE THREAD

**Issue by jadysonsilva** [sharpbrowser/SharpBrowser#25]
Hello, I have problems with RequestHandler and SchemeHandler classes. Apparently it is a mistake in the implementation. Help me solve this problem
![Erro_RequestHandler](https://user-images.githubusercontent.com/42219803/64017670-96aefe00-cb00-11e9-8281-67cb09abd11b.JPG)

**Comment by robinrodricks** [comment]
Just add a default implementation for those members:
1. Click on the base class at the top of RequestHandler
2. Right click Navigate To Definition
3. Copy the default implementations of the missing methods
4. Paste it into RequestHandler
5. Return the default value for each new method (eg. return 0 or return false)

**Comment by jadysonsilva** [comment]
Thank you my friend! Helped me a lot

**Comment by shooddelta** [comment]
I tried this but I don't think i am returning the correct information because I crash when I run.  This all worked before I updated to the news NuGet packages.  Could you paste a snippet of code for the 2 areas that will get this working again?

**Comment by AnErrupTion** [comment]
@shooddelta I have a fix for that :

Go to RequestHandler.cs, and replace this method :
`public IResourceRequestHandler GetResourceRequestHandler(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, IRequest request, bool isNavigation, bool isDownload, string requestInitiator, ref bool disableDefaultHandling)
        {
            throw new System.NotImplementedException();
        }`

by this one :
`public IResourceRequestHandler GetResourceRequestHandler(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, IRequest request, bool isNavigation, bool isDownload, string requestInitiator, ref bool disableDefaultHandling)
        {
            return null;
        }`

I hope that helped!

**Comment by xBonesz** [comment]
What about the SchemeHandler?

It seems like doing these changes corrupted everything for me so I would like to know what you would put in the missing implementations for the SchemeHandler, thanks.

**Comment by robinrodricks** [comment]
All fixed. Try updating your repo or download it again.
