### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by wycyxc** [sharpbrowser/SharpBrowser#3]
Is PAC supported in SharpBrowser?
Or I can select proxy server according to the url?

**Comment by hgupta9** [comment]
What do you mean by PAC?

**Comment by wycyxc** [comment]
PAC=Proxy Auto Config.
https://en.wikipedia.org/wiki/Proxy_auto-config

**Comment by hgupta9** [comment]
No its not supported, but if you have reference code in .NET it can be incorporated.

**Comment by wycyxc** [comment]
OK.Thanks.
