### ISSUE TITLE
Can't sign in to Google

### ISSUE THREAD

**Issue by VollRahm** [sharpbrowser/SharpBrowser#30]
When i try to sign into my Google account i get an error, that my browser is not allowed to sign in. Google has disabled logins from Embedded Frameworks [(Reference)](https://magpcss.org/ceforum/viewtopic.php?f=10&t=16717). I hope I can find a solution here for this problem.

**Comment by Daszbin** [comment]
I made a better version of SharpBrowser called Coder Nut it’s free to download its has all the features you want
Dark Mode
Bookmark Manager
History
Error reporting
Open pdf, doc & docx, excel files, PowerPoint files, music files and etc.
Ever changing updates like on a daily basis
Check it out
https://gamerslube.weebly.com/downloads.html
Download Coder Nut

**Comment by Daszbin** [comment]
I made a better version of SharpBrowser called Coder Nut it’s free to download its has all the features you want
Dark Mode
Bookmark Manager
History
Error reporting
Open pdf, doc & docx, excel files, PowerPoint files, music files and etc.
Ever changing updates like on a daily basis
Check it out
https://gamerslube.weebly.com/downloads.html
Download Coder Nut

**Comment by VollRahm** [comment]
I found a solution, just set the User agent to `Mozilla/5.0 (Some random text) Gecko/20100101 Firefox/70.0` using 
```cs
settings.CefCommandLineArgs.Add("--user-agent", "Mozilla/5.0 (Some random text) Gecko/20100101 Firefox/70.0");
```
