### ISSUE TITLE
Compiled Sharp Browser Exe is reportet by Antivirus Bitdefender as Gen:Variant.MSILPerseus.204881 (Trojan)

### ISSUE THREAD

**Issue by Hopfenspirger** [sharpbrowser/SharpBrowser#31]
Is Sharp Browser really dangerous?

**Comment by robinrodricks** [comment]
It's a false positive. We use trusted and reliable components like CefSharp
and CEF which are open source and vetted by the community. If you have any
issues don't use it.

**Comment by Hopfenspirger** [comment]
Hello Robin, thanks for the quick reply! OK - I also think it's a false positive. I just wanted to be sure... 
(...and let you know)

I'm also testing around with CefSharp and my Exe ist not reported. So the false positive is probably happening outside the CefSharp Code... I just have an eye on this because in modern times I use more and more open source code, which uses other open source code and so on - and so it is getting more and more difficult to keep track of all the code written by "strangers" and beeing executed in my apps...

Kind regards, Markus

**Comment by robinrodricks** [comment]
Hmmm. SharpBrowser is just a fancy wrapper over CefSharp. You can check we
hardly have like 10 classes implemented. Not sure why BD is flagging this.
