### ISSUE TITLE
Does CefSharp 79 support Flash?

### ISSUE THREAD

**Issue by AlrReady** [sharpbrowser/SharpBrowser#35]
I added Flash support to sharpbrowser code, but visiting the website still indicates that flash has expired. The flash version used is 32.0.0.192.
Added code:
settings.CefCommandLineArgs["enable-system-flash"] = "1";
settings.CefCommandLineArgs.Add("ppapi-flash-version", "32.0.0.192");
settings.CefCommandLineArgs.Add("ppapi-flash-path", @".\pepflashplayer.dll");

**Comment by heixiaoma** [comment]
Hello, I also encountered the same problem as you, and it has not been solved at present. Do you have a solution?

**Comment by h3xb0y** [comment]
try add `settings.CefCommandLineArgs.Add("enable-npapi", "1");`

**Comment by robinrodricks** [comment]
I'm not sure. You'll have to check in the CefSharp repo issue tracker for that.

**Comment by robinrodricks** [comment]
No plans to support Flash as Flash in the browser has reached EOL even by Adobe.
