### ISSUE TITLE
BrowserTabStrip.cs line 382 error

### ISSUE THREAD

**Issue by serhiy1994** [sharpbrowser/SharpBrowser#45]
In the BrowserTabStrip.cs file on the 382nd line the CLR returns an error: "the _ doesn't exist in the current context". How to fix it?

**Comment by vamsiikrishnaak** [comment]
_ indicates that the variable is a discard. (https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/discards)

Which version of .Net Framework are you using?

**Comment by serhiy1994** [comment]
> Which version of .Net Framework are you using?

4.6.

**Comment by robinrodricks** [comment]
I am not getting any compile errors using VS 2019 as of present.
