### ISSUE TITLE
can not download files automatic

### ISSUE THREAD

**Issue by lwdred** [sharpbrowser/SharpBrowser#5]
when i click a link to download a file.if the file is a pdf,it can be show on a new tab.but the others can not be show and can not be download automatic. any one can hele me? tks.

**Comment by lwdred** [comment]
public string CalcDownloadPath(DownloadItem item) {

			string path = item.SuggestedFileName != null ? item.SuggestedFileName.GetAfterLast(".") + " file" : "downloads";

			//string path = null;
			if (path != null) {
				return path;
			}

			return null;
		}

**Comment by hgupta9** [comment]
Can you check now? I've set the behavior to automatically open the Downloads tab when a download is started .. does it work for you?
