### ISSUE TITLE
Would it be worth releasing a distribution for non-developers?

### ISSUE THREAD

**Issue by LandarXT** [sharpbrowser/SharpBrowser#57]
There could be an (albeit small) percentage of people who may wish to get the software through traditional installation means, so perhaps we could offer this? I would be more than happy to be the one to compile these builds if this goes ahead.

**Comment by robinrodricks** [comment]
Whom do you suppose will be the potential users? As a browser its a pretty crappy product compared to say Chrome or Brave. My only reason for developing this was that developers who needed a white label browser or automatable browser could use this as a base.

**Comment by LandarXT** [comment]
I htought possibly people who needed a lightweight and fast browser, or those who simply didn't need all of the features of say Chrome, I understand there wouldn't be too high of a userbase but it's not really too much effort to zip up or create an MSI installer for the browser every week or two in my opinion.

**Comment by robinrodricks** [comment]
Yes a setup could be made, but I really doubt if we can compete with professional browser developed for 20+ years. An [InnoSetup ](https://jrsoftware.org/isinfo.php) build would be easy to make, since [VDProj is now dead](https://stackoverflow.com/questions/60724823/vdproj-is-incomatible-in-vs-2019-community-edition-and-reload-project-give). Yes advanced features are always welcome.

**Comment by LandarXT** [comment]
I have made an example Inno Setup installer [here](https://drive.google.com/file/d/1JpvasK02c-gEjYBjw64xWGYgJWA2f98n/view?usp=sharing).  As you can see it is a fully featured installer and only took around five minutes to make.

We could possibly make these builds every 1-2 weeks and if even 1 person uses it, I personally believe it would be beneficial for possibly evolving this browser. If you do not want to spend time making these builds, I could easily make them for you. However, if you truly believe there is no use for this installer, I am more than happy to accept your opinion as you are the project author.

**Comment by LandarXT** [comment]
By the way, as I see you do not agree with this, I have made the browsextra fork to release under my own branding - I will still contribute upstream

**Comment by robinrodricks** [comment]
> By the way, as I see you do not agree with this, I have made the browsextra fork to release under my own branding - I will still contribute upstream

I don't disagree with you, its just been difficult keeping up with all the open source projects going around.

I would ask that you do not fork as that would fracture the community further, as it is we have very few contributors.

You can make a setup build and place it under a 'setup' folder and make a PR for the same. You can then make another PR adding a link from the readme to the setup to 'advertise' it. Whatever other changes you want to make, you are free to raise PRs.

**Comment by robinrodricks** [comment]
Also make a PR for adding the innosetup description file into the repo.

**Comment by robinrodricks** [comment]
> We could possibly make these builds every 1-2 weeks and if even 1 person uses it, I personally believe it would be beneficial for possibly evolving this browser.

You are free to do it, I don't personally have the time to do it, but any updates you make you are free to raise PRs and I accept most PRs submitted.

**Comment by robinrodricks** [comment]
Please note I am not recieving github alerts for this project, as it is under a different user name (sharpbrowser rather than my name). So if you want me to reply to something please tag me like @robinrodricks .

**Comment by robinrodricks** [comment]
Hi @LandarXT  - Can you please make a PR and include the innosetup project file inside the setup folder? So that way I or any other OSS user can also make a setup if needed.
