### ISSUE TITLE
Does not load web pages fully / loads with incomplete layout

### ISSUE THREAD

**Issue by QuickWhitt7** [sharpbrowser/SharpBrowser#7]
![sharpbrowser display bug for windows 10](https://cloud.githubusercontent.com/assets/24725571/26515565/f22112e2-4249-11e7-8846-58e38912b29c.png)

If it is of any support, I am running the latest version of Windows 10 on an HP computer with 3.4GHz processor and 8GB of RAM.

**Comment by QuickWhitt7** [comment]
Now that I think about it, it could be because the program is not equipped to handle larger than normal screen sizes. I have a 23-inch Roku TV for a computer monitor, maybe that would be the cause?

**Comment by hgupta9** [comment]
We have just used simple Docking to ensure the browser is as big as the window. The black area I think is a CefSharp bug. Why don't you add a bug report here : https://github.com/cefsharp/CefSharp/issues
