### ISSUE TITLE
Can a VPN be added?

### ISSUE THREAD

**Issue by TwangyMoney** [sharpbrowser/SharpBrowser#71]
I always use a vpn in my browsers. Is this built from chromium? Uhm sorry for my lack of knowledge. But would there be a way for me to add a vpn that's active all the time? Or maybe there would be a button that toggles it? Maybe a way to add custom vpns created from OpenVPN?

**Comment by robinrodricks** [comment]
You mean add proxy settings? Check upstream if its supported on [CefSharp](https://github.com/cefsharp/CefSharp/), if it is, we can add something.

**Comment by TwangyMoney** [comment]
Damn I don't know what any of that means. I'll try, I guess.

**Comment by TwangyMoney** [comment]
I think I found something but I'm not sure.

> http://groups.google.com/g/cefsharp/c/Nv6DexNsEdY

> https://search.yahoo.com/yhs/search?p=does+cefsharp+support+proxy+settings&hspart=iba&hsimp=yhs-syn_launcham&param2=9dUI1n2R0BLDxNuWfiP4aSFOTltNdSPoIx38%2BUf%2FiXrvPdoGmStdlfwLFZYDvqkAJrWWk4yNReCLnBD%2FqPsDZd7olTZcV8HMx1G%2Fk786sE2Tis1g8dJd8zxVWs%2BbKztBnq1TfqUiqPYK9pXifXmJFyorDuCsYXJE71Y6G5tfejB5RvhVpZuEfgJortQz5SnnqkFDTzBYESr2mtsTdV8rdF%2FR4PHBax2IkrAyCQJhuBYUeyy9rg2wBDWqJMIsFYpgylVFGwtVhDOCd6jSUzl4rqdBb8MqOcFxbv7RET2ViVxnzQJs8ynvDcq300xMzHph&param3=HpCyCT2cXaKG4CVDR00rqgObRQahimQNt2d5ZCR7Jy3IZoD3T11qaq2nywASZYgKGWhMz2gzOeKFw2qtE5kIUotiw81ZsxcL9gO%2F%2BPhSEjAU92w%2FUY8Vt7OU3PcAKwOTqKytNQUmycB6dLyOIFihgdujuRhsERSrPtvpD%2From7VgzKDrl7w3gboncoiquDurn2XZtiyhB%2F24tl1VR6ipAD%2BFM53xg%2FOPOsp3JECsKNJB4RgfiSrZo9UKyNaZyJk0%2Bw%2FGqyEcpHdnMfUnrcJuaG0qm4u4S3kc2xFigeGNfDskLYOOqdpW3VVp2OaNiQnfJHESAMoM%2FeF0jvLWlM6YMA%3D%3D&type=f2%3A%3B.6850610d4680680b2811f3dcdca6be379af%3B5.ac48522a20946644e52a8ef8e64166f19c0ca9cdf89835745bb551d3fa4fa48ff4f1c70ddbdeb8cec0f0defadc4fd6a4408b0

**Comment by TwangyMoney** [comment]
If this works out, bro I love you.

**Comment by TwangyMoney** [comment]
In any case, is there a different way to put an icon in the title bar? Mine broke maybe causeI did something.

**Comment by robinrodricks** [comment]
Icon is set here - https://github.com/sharpbrowser/SharpBrowser/blob/master/src/MainForm.cs#L62

You need any ICO resource and we set it manually to bypass a windows bug.

**Comment by TwangyMoney** [comment]
Oh, thank you man. Tho I removed it last time cause it gave me errors. After I removed it, the errors stopped appearing. If it appears again maybe I could let you know.

**Comment by TwangyMoney** [comment]
About the vpn thing, could something be done?
