### ISSUE TITLE
Can a VPN be added?

### ISSUE THREAD

**Issue by TwangyMoney** [sharpbrowser/SharpBrowser#72]
I wanted to say, my last issue got closed without my problem being solved. I wanted to add a vpn/proxy to the browser. How can I do so? And yes I think Cefsharp supports proxy settings.

**Comment by robinrodricks** [comment]
Set "Proxy" to true and hard code the proxy settings you need.

https://github.com/sharpbrowser/SharpBrowser/blob/master/src/Browser/BrowserConfig.cs#L28
