### ISSUE TITLE
Some websites don't load/video players don't load

### ISSUE THREAD

**Issue by TwangyMoney** [sharpbrowser/SharpBrowser#74]
Video players on some websites like bciptv.net doesn't load. I thought most websites are supposed to load here. Any fixes?
![image](https://user-images.githubusercontent.com/87775970/205716213-133676e5-acc3-4688-a92d-366a258a5cca.png)

**Comment by TwangyMoney** [comment]
It's just blank after I press the play button.
![image](https://user-images.githubusercontent.com/87775970/205716548-1758814c-80c5-4a46-b08a-3b81aa2bff53.png)

**Comment by TwangyMoney** [comment]
This is how it should look like. There's a live video playing.
![image](https://user-images.githubusercontent.com/87775970/205716704-007908ca-d1d1-48bc-9ceb-1b5cb91b0b3d.png)

**Comment by robinrodricks** [comment]
File an issue upstream at CefSharp. This is just a wrapper app.

Also, this is not a commercial product, please stop expecting hand holding to debug every possible use case.
