### ISSUE TITLE
Sharpborwser compatible with WPF ?

### ISSUE THREAD

**Issue by sireneweb** [sharpbrowser/SharpBrowser#8]
Hi, i'm wondering if sharpbrowser is compatible with WPF ?

**Comment by robinrodricks** [comment]
No not yet but I can make such a version...

**Comment by andrewjoseofficial** [comment]
@robin rodricks

**Comment by andrewjoseofficial** [comment]
@robinrodricks Can you make a feature for save image file as?

**Comment by robinrodricks** [comment]
Not currently, no.
