### ISSUE TITLE
I will never use your browser again!

### ISSUE THREAD

**Issue by DarkCodeStudios** [sharpbrowser/SharpBrowser#90]
Using a fairly powerful computer and starting your browser and doing all the steps just before the code completes my computer gives a "blue screen of death" and it forms formatted my computer, losing files worth 20000CHF...

DarkCodeStudios

**Comment by robinrodricks** [comment]
Show some proof. Also, did you compile from source or use the installer?

**Comment by DarkCodeStudios** [comment]
> Show some proof. Also, did you compile from source or use the installer?

Obviously I wasn't recording a video, but I did install it. Or I can send you the photo of the error screen but on discord

**Comment by DarkCodeStudios** [comment]
Perfect... There will be consequences
